#!/bin/sh

if ! ls "$HOME"/.config/shadowreplay;then
    cp example_config "$HOME"/.config/shadowreplay
fi

DIR=$(dirname "$0")

# Install dependencies on Arch
if [ -e "/etc/arch-release" ]; then
    echo "Installing dependencies"
    sudo pacman --noconfirm -S xdotool ffmpeg libnotify
fi

# move shadowreplay to /usr/local/bin
sudo install "$DIR/shadowreplay" /usr/local/bin 

# set up keybinds ..
STARTSR="setsid /usr/local/bin/shadowreplay &>/tmp/shadowreplay.log"
STOPSR="killall shadowreplay & killall ffmpeg"
SAVECLIP="""killall --user "$USER" --ignore-case -signal SIGTERM ffmpeg && setsid /usr/local/bin/shadowreplay &>/tmp/shadowreplay.log"""

# ..if i3 is in use
if ls /bin/i3;then
    echo """
    bindsym $mod+F9 "exec $SAVECLIP"
    bindsym $mod+Alt+F9 "exec $STARTSR" 
    bindsym $mod+Alt+F10 "exec $STOPSR"
    """ >> "$HOME/.config/i3/config"
# ..if sxhkd
elif ls /bin/sxhkd;then
   echo """
   super + F9
        $SAVECLIP
   super + alt + F9
        $STARTSR
   super + alt + F10
        $STOPSR
   """ >> "$XDG_CONFIG_HOME/sxhkd/sxhkdrc"
# ..if xbindkeys is installed
elif ls /bin/xbindkeys;then
    echo """
    # make F9 save ShadowRePlay replay
    "$SAVECLIP"
       F9
    
    # make alt+F9 turn ShadowRePlay on
    "$STARTSR"
       Alt+F9

    # make alt+F10 turn ShadowRePlay off
    "$STOPSR"
       Alt+F10
    """ >> "$HOME/.xbindkeysrc"
fi

echo """

Installation complete!
Press Alt+F9 to start ShadowReplay, then F9 to save a replay!
Alt+F10 will shut it down."""
