#!/bin/sh

if ! ls "$HOME"/.config/shadowreplay;then
    cp example_config "$HOME"/.config/shadowreplay
fi

DIR=$(dirname "$0")

# Install dependencies on Arch
if [ -e "/etc/arch-release" ]; then
    echo "Installing dependencies"
    sudo pacman -S ffmpeg libnotify xdotool
fi

# move shadowreplay to /usr/local/bin
echo "Installing from $DIR to /usr/local/bin.."
sudo install "$DIR/shadowreplay" /usr/local/bin 

# set up keybinds ..
NOTIFY="notify-send ShadowRePlay "
STARTSR="shadowreplay"
STOPSR="killall shadowreplay & killall -s1 ffmpeg"
SAVECLIP="""killall --user \\\"\$USER\\\" --ignore-case -signal SIGTERM ffmpeg"""

# ..if i3 is in use
if ls /bin/i3;then
    echo """
bindsym F9 \"exec $SAVECLIP\"
bindsym \$mod+F9 \"exec $STARTSR; exec $NOTIFY Running!\" 
bindsym \$mod+F10 \"exec $STOPSR\; exec $NOTIFY Stopping...\"
    """ >> "$HOME/.config/i3/config"
# ..if sxhkd
elif ls /bin/sxhkd;then
   echo """
F9
    $SAVECLIP
super + F9
    $STARTSR;$NOTIFY Running!
super + F10
    $STOPSR;$NOTIFY Stopping...
   """ >> "$XDG_CONFIG_HOME/sxhkd/sxhkdrc"
# ..if xbindkeys is installed
elif ls /bin/xbindkeys;then
    echo """
# make F9 save ShadowRePlay replay
\"$SAVECLIP\"
    F9
    
# make meta+F9 turn ShadowRePlay on
\"$STARTSR;$NOTIFY Running!\"
    Super_L + F9

# make meta+F10 turn ShadowRePlay off
\"$STOPSR\;$NOTIFY Stopping...\"
    Super_L + F10
    """ >> "$HOME/.xbindkeysrc"
fi

echo """

Installation complete!
Press Meta+F9 to start ShadowReplay, then F9 to save a replay!
Meta+F10 will shut it down."""
